### ISSUE TITLE
Testing validateForInsert()

### ISSUE THREAD

**Issue by paulhoadley** [hprange/wounit#47]
I have an EO that splits some save-time validation logic between `validateForSave()` and `validateForInsert()`, with the latter method being called just for new objects. I can't test this using something like `confirm(eo, canBeSaved())`, because `CanBeSavedMatcher.matchesWithPossibleException()` only calls `validateForSave()`. Obviously I could test it directly by calling `validateForInsert()`, but could we get WOUnit to do this for us? I see a couple of possibilities:
- A new `CanBeInsertedMatcher`.
- Adding a call to `validateForInsert()` to `CanBeSavedMatcher.matchesWithPossibleException()` on the condition that `isNewObject()` was true.

Would either of these approaches be suitable, and which would be preferred? I am happy to do the work and open a PR, though it's not clear whether WOUnit development is ongoing—let me know!

**Comment by hprange** [comment]
Hi Paul,

Not calling `validateForInsert` when the object is new is certainly a bug. The second option sounds like the correct fix.

I've been very busy lately, but I'm planning to make a revamped WOUnit version compatible with JUnit 5 in the future. Anyway, I'm glad to make new releases of WOUnit with bug fixes in the near future.

**Comment by paulhoadley** [comment]
> I'm planning to make a revamped WOUnit version compatible with JUnit 5 in the future.

Sounds great! Any chance of bumping up to Wonder 7 at the same time? I currently run a custom build of WOUnit because of a binary incompatibility issue there, but it would be great to come back to a mainline release.

**Comment by hprange** [comment]
Certainly, I'll make a release of WOUnit compatible with Wonder 7. We just need to make a release of Wonder 7 before that. :)
